// examples/react-hoc/src/App.tsx
import { Component } from "react";
import reactLogo from "./assets/react.svg";
import viteLogo from "/vite.svg";
import "./App.css";
import { i18nValue } from "localiz";
import { withTranslation } from "localiz/react";

interface Props {
  t?: i18nValue["t"];
  i18n?: i18nValue;
}

interface State {
  count: number;
}

class App extends Component<Props, State> {
  state: Readonly<State> = {count: 0}

  render() {
    return (
      <>
        <div>
          <a href="https://vite.dev" target="_blank">
            <img src={viteLogo} className="logo" alt="Vite logo" />
          </a>
          <a href="https://react.dev" target="_blank">
            <img src={reactLogo} className="logo react" alt="React logo" />
          </a>
        </div>
        <h1>Vite + React</h1>
        <p>text : {this.props.t?.("hello", {name : "Jhon doe"})}</p>
        <div className="card">

          <button onClick={() => this.props.i18n?.changeLanguage("en")}>en</button>
          <button onClick={() => this.props.i18n?.changeLanguage("es")}>es</button>

          <button
            onClick={() =>
              this.setState((state) => ({
                ...state,
                count: state.count + 1,
              }))
            }
          >
            count is {this.state.count}
          </button>
          <p>
            Edit <code>src/App.tsx</code> and save to test HMR
          </p>
        </div>
        <p className="read-the-docs">
          Click on the Vite and React logos to learn more
        </p>
      </>
    );
  }
}

export default withTranslation(App);

// examples/vue/src/App.vue
<script setup lang="ts">
import { reactive } from "vue";
import { useTranslation, useValue } from "localiz/vue";
import HelloWorld from "./components/HelloWorld.vue";

const { i18n } = useTranslation();

const options = reactive({ name: "jhon doe" });
const helloValue = useValue("hello", options);

const onChangeLanguage = () => {
  i18n.changeLanguage(i18n.language === "en" ? "es" : "en");
};

const onChangeName = () => {
  options.name = options.name === "jane doe" ? "jhon doe" : "jane doe";
};
</script>

<template>
  <div>
    <a href="https://vite.dev" target="_blank">
      <img src="/vite.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
  </div>
  <p>{{ helloValue }}</p>
  <button @click="onChangeLanguage">change language</button>
  <button @click="onChangeName">change name</button>
  <HelloWorld msg="Vite + Vue" />
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
